# permissions for end users to edit platformfeatures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platformfeature-editor-role
rules:
- apiGroups:
  - jx.jenkins-x.io
  resources:
  - platformfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jx.jenkins-x.io
  resources:
  - platformfeatures/status
  verbs:
  - get
