# permissions for end users to view platformfeatures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platformfeature-viewer-role
rules:
- apiGroups:
  - jx.jenkins-x.io
  resources:
  - platformfeatures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jx.jenkins-x.io
  resources:
  - platformfeatures/status
  verbs:
  - get
